decimalValue = 10;
print("This is a Decimal Value : ", decimalValue);
binaryValue1 = 0b111;
print("This is a Binary Value using 'b' : ", binaryValue1);
binaryValue2 = 0B111;
print("This is a Binary Value using 'B' : ", binaryValue2);
octalValue1 = 0o777;
print("This is an Octal Value using 'o' : ", octalValue1);
octalValue2 = 0O777;
print("This is an Octal Value using 'O' : ", octalValue2);
hexaDecimalValue1 = 0xface;
print("This is a Hex-Decimal Value using 'x' : ", octalValue1);
hexaDecimalValue2 = 0XFace;
print("This is a Hexa-Decimal Value using 'X' : ", octalValue1);
print("----------------------------------------------------------------------------------");
print("After converting Decimal to Binary using Conversion method bin() : ", bin(decimalValue));
print("After converting Octal to Binary using Conversion method bin() : ", bin(octalValue1));
print("After converting Hexa-Decimal to Binary using Conversion method bin() : ", bin(hexaDecimalValue1));
print("----------------------------------------------------------------------------------");
print("After converting Binary to Octal using Conversion method oct() : ", oct(binaryValue1));
print("After converting Decimal to Octal using Conversion method oct() : ", oct(decimalValue));
print("After converting Hexa-Decimal to Octal using Conversion method oct() : ", oct(hexaDecimalValue1));
print("----------------------------------------------------------------------------------");
print("After converting Binary to Hexa-Decimal using Conversion method hex() : ", hex(binaryValue1));
print("After converting Decimal to Hexa-Decimal using Conversion method hex() : ", hex(decimalValue));
print("After converting Octal to Hexa-Decimal using Conversion method hex() : ", hex(octalValue1));
print("----------------------------------------------------------------------------------");